CREATE TABLE IF NOT EXISTS silver.substitutions (
    key_id INT PRIMARY KEY,
    substitution_id VARCHAR(255),
    tournament_id VARCHAR(255),
    tournament_name VARCHAR(255),
    match_id VARCHAR(255),
    match_name VARCHAR(255),
    match_date DATE,
    stage_name VARCHAR(255),
    group_name VARCHAR(255),
    team_id VARCHAR(255),
    team_name VARCHAR(255),
    team_code VARCHAR(255),
    home_team INT,
    away_team INT,
    player_id VARCHAR(255),
    family_name VARCHAR(255),
    given_name VARCHAR(255),
    shirt_number INT,
    minute_label VARCHAR(255),
    minute_regulation INT,
    minute_stoppage INT,
    match_period VARCHAR(255),
    going_off INT,
    coming_on INT
);
