CREATE TABLE IF NOT EXISTS silver.bookings (
    booking_id VARCHAR(255) PRIMARY KEY,
    tournament_id VARCHAR(255),
    tournament_name VARCHAR(255),
    match_id VARCHAR(255),
    match_name VARCHAR(255),
    match_date DATE,
    stage_name VARCHAR(255),
    group_name VARCHAR(255),
    team_id VARCHAR(255),
    team_name VARCHAR(255),
    team_code VARCHAR(10),
    home_team VARCHAR(255),
    away_team VARCHAR(255),
    player_id VARCHAR(255),
    family_name VARCHAR(255),
    given_name VARCHAR(255),
    shirt_number INT,
    minute_label VARCHAR(10),
    minute_regulation INT,
    minute_stoppage INT,
    match_period VARCHAR(50),
    yellow_card INT,
    red_card INT,
    second_yellow_card INT,
    sending_off INT
);
