CREATE TABLE IF NOT EXISTS silver.goals (
    goal_id VARCHAR(255) PRIMARY KEY,
    tournament_id VARCHAR(255),
    tournament_name VARCHAR(255),
    match_id VARCHAR(255),
    match_name VARCHAR(255),
    match_date DATE,
    stage_name VARCHAR(255),
    group_name VARCHAR(255),
    team_id VARCHAR(255),
    team_name VARCHAR(255),
    team_code VARCHAR(10),
    home_team INTEGER,
    away_team INTEGER,
    player_id VARCHAR(255),
    family_name VARCHAR(255),
    given_name VARCHAR(255),
    shirt_number INTEGER,
    player_team_id VARCHAR(255),
    player_team_name VARCHAR(255),
    player_team_code VARCHAR(10),
    minute_label VARCHAR(10),
    minute_regulation INTEGER,
    minute_stoppage INTEGER,
    match_period VARCHAR(255),
    own_goal INTEGER,
    penalty INTEGER
);
