INSERT INTO silver.tournaments (
    key_id, 
    tournament_id, 
    tournament_name, 
    year, 
    start_date, 
    end_date, 
    host_country, 
    winner, 
    host_won, 
    count_teams, 
    group_stage, 
    second_group_stage, 
    final_round, 
    round_of_16, 
    quarter_finals, 
    semi_finals, 
    third_place_match, 
    final
)
SELECT 
    key_id, 
    tournament_id, 
    INITCAP(tournament_name) AS tournament_name, 
    year, 
    start_date::DATE, 
    end_date::DATE, 
    INITCAP(host_country) AS host_country, 
    INITCAP(winner) AS winner, 
    host_won, 
    count_teams, 
    group_stage, 
    second_group_stage, 
    final_round, 
    round_of_16, 
    quarter_finals, 
    semi_finals, 
    third_place_match, 
    final
FROM bronze.tournaments;
