INSERT INTO silver.group_standings (
    key_id,
    tournament_id, 
    tournament_name, 
    stage_number, 
    stage_name, 
    group_name, 
    position, 
    team_id, 
    team_name, 
    team_code, 
    played, 
    wins, 
    draws, 
    losses, 
    goals_for, 
    goals_against, 
    goal_difference, 
    points, 
    advanced
)
SELECT 
    key_id,
    tournament_id, 
    INITCAP(tournament_name) AS tournament_name, 
    stage_number, 
    INITCAP(stage_name) AS stage_name, 
    INITCAP(group_name) AS group_name, 
    position, 
    team_id, 
    INITCAP(team_name) AS team_name, 
    team_code, 
    played, 
    wins, 
    draws, 
    losses, 
    goals_for, 
    goals_against, 
    goal_difference, 
    points, 
    advanced
FROM bronze.group_standings;
