INSERT INTO silver.player_appearances (
    key_id, 
    tournament_id, 
    tournament_name, 
    match_id, 
    match_name, 
    match_date, 
    stage_name, 
    group_name, 
    team_id, 
    team_name, 
    team_code, 
    home_team, 
    away_team, 
    player_id, 
    family_name, 
    given_name, 
    shirt_number, 
    position_name, 
    position_code, 
    starter, 
    substitute, 
    captain
)
SELECT 
    key_id, 
    tournament_id, 
    INITCAP(tournament_name) AS tournament_name, 
    match_id, 
    INITCAP(match_name) AS match_name, 
    match_date::DATE, 
    INITCAP(stage_name) AS stage_name, 
    INITCAP(group_name) AS group_name, 
    team_id, 
    INITCAP(team_name) AS team_name, 
    team_code, 
    home_team, 
    away_team, 
    player_id, 
    INITCAP(family_name) AS family_name, 
    INITCAP(given_name) AS given_name, 
    shirt_number, 
    INITCAP(position_name) AS position_name, 
    position_code, 
    starter, 
    substitute, 
    captain
FROM bronze.player_appearances;
