INSERT INTO silver.team_appearances (
    key_id, 
    tournament_id, 
    tournament_name, 
    match_id, 
    match_name, 
    stage_name, 
    group_name, 
    group_stage, 
    knockout_stage, 
    replayed, 
    replay, 
    match_datetime, 
    stadium_id, 
    stadium_name, 
    city_name, 
    country_name, 
    team_id, 
    team_name, 
    team_code, 
    opponent_id, 
    opponent_name, 
    opponent_code, 
    home_team, 
    away_team, 
    goals_for, 
    goals_against, 
    goal_differential, 
    extra_time, 
    penalty_shootout, 
    penalties_for, 
    penalties_against, 
    result, 
    win, 
    lose, 
    draw
)
SELECT 
    key_id, 
    tournament_id, 
    INITCAP(tournament_name) AS tournament_name, 
    match_id, 
    INITCAP(match_name) AS match_name, 
    INITCAP(stage_name) AS stage_name, 
    INITCAP(group_name) AS group_name, 
    group_stage, 
    knockout_stage, 
    replayed, 
    replay, 
    (match_date || ' ' || match_time)::TIMESTAMP AS match_datetime,  -- Combine date and time
    stadium_id, 
    INITCAP(stadium_name) AS stadium_name, 
    INITCAP(city_name) AS city_name, 
    INITCAP(country_name) AS country_name, 
    team_id, 
    INITCAP(team_name) AS team_name, 
    team_code, 
    opponent_id, 
    INITCAP(opponent_name) AS opponent_name, 
    opponent_code, 
    home_team, 
    away_team, 
    goals_for, 
    goals_against, 
    goal_differential, 
    extra_time, 
    penalty_shootout, 
    penalties_for, 
    penalties_against, 
    INITCAP(result) AS result, 
    win, 
    lose, 
    draw
FROM bronze.team_appearances;
